# Generated by Django 2.0.4 on 2018-04-30 15:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentsProfile',
            new_name='PaymentProfile',
        ),
    ]
