# Generated by Django 2.0.4 on 2018-05-02 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.PaymentProfile'),
        ),
    ]
