# Generated by Django 2.0.4 on 2018-05-02 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_applicant_interest'),
        ('payments', '0007_order_payment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='user',
        ),
        migrations.AddField(
            model_name='voucher',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Company'),
        ),
    ]
