# Generated by Django 2.0.4 on 2018-05-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_order_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('abandoned', 'Abandoned')], default='created', max_length=50),
        ),
    ]
