# Generated by Django 2.0.4 on 2018-04-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20180424_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
