# Generated by Django 2.0.4 on 2018-04-25 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20180425_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Industry'),
        ),
        migrations.DeleteModel(
            name='Industry',
        ),
    ]
