# Generated by Django 2.0.4 on 2018-04-28 16:21

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_application_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='resume',
            field=models.FileField(null=True, upload_to=jobs.models.user_directory_path),
        ),
    ]
