# Generated by Django 2.0.4 on 2018-05-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_voucher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('status', models.CharField(choices=[('created', 'Created'), ('paid', 'Paid')], max_length=50)),
            ],
        ),
    ]
