# Generated by Django 2.0.4 on 2018-05-03 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.Order'),
        ),
    ]
