# Generated by Django 2.0.4 on 2018-04-23 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180423_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('location', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('about', models.TextField(blank=True, null=True)),
                ('exprience_years', models.PositiveIntegerField(verbose_name='Years of Experience')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
