# Generated by Django 2.0.4 on 2018-04-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_applicant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='company name')),
                ('description', models.TextField(verbose_name='describe your company')),
                ('website', models.URLField(verbose_name='company webite')),
                ('country', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=120, verbose_name='company address')),
            ],
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='exprience_years',
            new_name='years_of_exp',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='location',
            field=models.CharField(max_length=20, verbose_name='Where do you Reside now'),
        ),
    ]
