# Generated by Django 2.0.4 on 2018-04-25 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_industry'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='interest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Industry'),
        ),
    ]
