# Generated by Django 2.0.4 on 2018-04-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180423_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Where do you Reside now'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='years_of_exp',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Years of Experience'),
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='company address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='describe your company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='company name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='company webite'),
        ),
    ]
