# Generated by Django 2.0.4 on 2018-05-03 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_charge_order'),
        ('jobs', '0010_application_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='voucher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.Voucher'),
        ),
    ]
